# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86d272e1b54961fb13ec734b51b7c5df87f070bee1fa27ddff29d272a8de01a807e432ff57260b68b169ace55f8b5c122d851c1287043136d7eadcfc3cb65b54

test:
  secret_key_base: 2dfc1bc1d7dfbcd7c8772d04f3e523e45b8008790351a6b0560a4db7f462316eb7ed2d82dfa98de04d53996871266e44706f61401941ac2e320ced9c062ecbcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
